INSERT INTO categorie (categoria) VALUES
('Accessori moda'),
('Arredamento'),
('Articoli per la casa'),
('Borse'),
('Candele'),
('Carta'),
('Ceramica'),
('Cosmetici naturali'),
('Decorazioni'),
('Fiori e piante'),
('Gioielli'),
('Giocattoli'),
('Lampade'),
('Legno'),
('Pelle'),
('Quadri'),
('Saponi e profumi'),
('Strumenti musicali'),
('Tessuti'),
('Vetro');
