services:
    db-artigianato_online:
        build: ./db
        container_name: pgdb-artigianato_online
        restart: always
        ports:
            - "6543:5432"
        volumes:
            - pg_artigianato_online:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: artigianato_online
            POSTGRES_HOST: localhost
            POSTGRES_DB: artigianato_online_db
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432

    backend:
        build: ./backend
        container_name: backend-artigianato_online
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db-artigianato_online
        environment:
            POSTGRES_USER: artigianato_online
            POSTGRES_HOST: db-artigianato_online
            POSTGRES_DB: artigianato_online_db
            POSTGRES_PASSWORD: password
            POSTGRES_PORT: 5432
            JWT_SECRET: jwtsecret
            JWT_TTL: '1h'
            IP_ADDRESS: localhost
            PORT: '8080'
            PROTOCOL: http

    frontend:
        build: ./frontend
        container_name: frontend-artigianato_online
        restart: always
        ports:
            - "127.0.0.1:8000:8000"
        environment:
            IP_ADDRESS: localhost
            PORT: '8000'
            BACKEND_URL: http://backend:8080
            PROTOCOL: http
        depends_on:
            - backend

volumes:
    pg_artigianato_online:
        driver: local
