services:
    db:
        build: ./db
        container_name: pgdb-artigianato_online
        restart: always
        ports:
            - "6543:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
    
    backend:
        build: ./backend
        container_name: backend-artigianato_online
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db

    frontend:
        build: ./frontend
        container_name: frontend-artigianato_online
        restart: always
        ports:
            - "8000:8000"

volumes:
    pgdata:
